name: financeiro-master

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - PORT=8000
      - DEBUG=1
      - SECRET_KEY=django-insecure-!0)_0s7*0u4u9z8yr(mm$$^qt$$mrvran(ej9z-te!(m0-yi=d7
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=financeiro_db
      - POSTGRES_USER=financeiro_user
      - POSTGRES_PASSWORD=financeiro_pass
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
