version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-!0)_0s7*0u4u9z8yr(mm$$^qt$$mrvran(ej9z-te!(m0-yi=d7
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  static_volume:
  media_volume: