# Generated by Django 5.2.6 on 2025-10-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('DESPESA', 'Despesa'), ('RECEITA', 'Receita')], max_length=20, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'db_table': 'api_classificacao',
                'indexes': [models.Index(fields=['descricao'], name='api_classif_descric_5a5220_idx'), models.Index(fields=['tipo'], name='api_classif_tipo_efef48_idx'), models.Index(fields=['ativo'], name='api_classif_ativo_598a60_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('documento', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('tipo', models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('FATURADO', 'Faturado')], max_length=20, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'api_pessoas',
                'indexes': [models.Index(fields=['documento'], name='api_pessoas_documen_7e56a2_idx'), models.Index(fields=['tipo'], name='api_pessoas_tipo_3b732a_idx'), models.Index(fields=['ativo'], name='api_pessoas_ativo_41eba4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimentoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número NF')),
                ('serie_nf', models.CharField(blank=True, max_length=10, null=True, verbose_name='Série NF')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data Emissão')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('quantidade_parcelas', models.IntegerField(default=1, verbose_name='Quantidade Parcelas')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.classificacao', verbose_name='Classificação')),
                ('faturado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_faturado', to='api.pessoas', verbose_name='Faturado')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_fornecedor', to='api.pessoas', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Movimento de Contas',
                'verbose_name_plural': 'Movimentos de Contas',
                'db_table': 'api_movimentocontas',
            },
        ),
        migrations.CreateModel(
            name='ParcelasContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField(verbose_name='Número da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data Vencimento')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Parcela')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='api.movimentocontas', verbose_name='Movimento')),
            ],
            options={
                'verbose_name': 'Parcela de Contas',
                'verbose_name_plural': 'Parcelas de Contas',
                'db_table': 'api_parcelascontas',
                'indexes': [models.Index(fields=['movimento'], name='api_parcela_movimen_5f26bf_idx'), models.Index(fields=['data_vencimento'], name='api_parcela_data_ve_dcf75a_idx'), models.Index(fields=['numero_parcela'], name='api_parcela_numero__c51560_idx'), models.Index(fields=['ativo'], name='api_parcela_ativo_aebee2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='movimentocontas',
            index=models.Index(fields=['fornecedor'], name='api_movimen_fornece_16dc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocontas',
            index=models.Index(fields=['faturado'], name='api_movimen_faturad_8a778f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocontas',
            index=models.Index(fields=['classificacao'], name='api_movimen_classif_0d36ab_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocontas',
            index=models.Index(fields=['data_emissao'], name='api_movimen_data_em_098323_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocontas',
            index=models.Index(fields=['ativo'], name='api_movimen_ativo_4a88e0_idx'),
        ),
    ]
