# Generated by Django 5.2.6 on 2025-11-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocontas',
            name='itens_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Itens (JSON)'),
        ),
    ]
